export const products = [
  {
    name: "Content King",
    category: "content distribution",
    language: "English",
    region: "USA",
    product_type: "web 3.0",
    price: 1000,
  },
  {
    name: "Distribución Total",
    category: "content distribution",
    language: "Spanish",
    region: "Spain",
    product_type: "Gambling",
    price: 800,
  },
  {
    name: "内容分发",
    category: "content distribution",
    language: "Chinese",
    region: "China",
    product_type: "adult",
    price: 1200,
  },
  {
    name: "AdMax",
    category: "Ads",
    language: "English",
    region: "UK",
    product_type: "web 3.0",
    price: 1500,
  },
  {
    name: "Publicité Plus",
    category: "Ads",
    language: "French",
    region: "France",
    product_type: "Gambling",
    price: 900,
  },
  {
    name: "Werbung Pro",
    category: "Ads",
    language: "German",
    region: "Germany",
    product_type: "adult",
    price: 1100,
  },
  {
    name: "Twitter Titan",
    category: "twitter influencer",
    language: "English",
    region: "USA",
    product_type: "web 3.0",
    price: 2000,
  },
  {
    name: "ツイッター影響者",
    category: "twitter influencer",
    language: "Japanese",
    region: "Japan",
    product_type: "Gambling",
    price: 1700,
  },
  {
    name: "트위터 인플루언서",
    category: "twitter influencer",
    language: "Korean",
    region: "South Korea",
    product_type: "adult",
    price: 1900,
  },
  {
    name: "Telegram Titan",
    category: "Telegram Influencer",
    language: "English",
    region: "Canada",
    product_type: "web 3.0",
    price: 1800,
  },
  {
    name: "Телеграм Инфлюенсер",
    category: "Telegram Influencer",
    language: "Russian",
    region: "Russia",
    product_type: "Gambling",
    price: 1300,
  },
  {
    name: "مؤثر تلغرام",
    category: "Telegram Influencer",
    language: "Arabic",
    region: "UAE",
    product_type: "adult",
    price: 1600,
  },
  {
    name: "YouTube Star",
    category: "Youtube influencers",
    language: "English",
    region: "Australia",
    product_type: "web 3.0",
    price: 2500,
  },
  {
    name: "Influencer de YouTube",
    category: "Youtube influencers",
    language: "Spanish",
    region: "Mexico",
    product_type: "Gambling",
    price: 2200,
  },
  {
    name: "Influenciador de YouTube",
    category: "Youtube influencers",
    language: "Portuguese",
    region: "Brazil",
    product_type: "adult",
    price: 2400,
  },
  {
    name: "InstaInfluencer",
    category: "instagram influencers",
    language: "English",
    region: "UK",
    product_type: "web 3.0",
    price: 3000,
  },
  {
    name: "इंस्टाग्राम प्रभावकार",
    category: "instagram influencers",
    language: "Hindi",
    region: "India",
    product_type: "Gambling",
    price: 2700,
  },
  {
    name: "Influencer di Instagram",
    category: "instagram influencers",
    language: "Italian",
    region: "Italy",
    product_type: "adult",
    price: 2900,
  },
  {
    name: "IOC King",
    category: "IOC Listing",
    language: "English",
    region: "USA",
    product_type: "web 3.0",
    price: 5000,
  },
  {
    name: "Listado IOC",
    category: "IOC Listing",
    language: "Spanish",
    region: "Spain",
    product_type: "Gambling",
    price: 4500,
  },
  {
    name: "Liste IOC",
    category: "IOC Listing",
    language: "French",
    region: "France",
    product_type: "adult",
    price: 4800,
  },
  {
    name: "Exchange Pro",
    category: "Exchange listing",
    language: "English",
    region: "Singapore",
    product_type: "web 3.0",
    price: 10000,
  },
  {
    name: "交易所上市",
    category: "Exchange listing",
    language: "Chinese",
    region: "China",
    product_type: "Gambling",
    price: 9500,
  },
  {
    name: "거래소 상장",
    category: "Exchange listing",
    language: "Korean",
    region: "South Korea",
    product_type: "adult",
    price: 9800,
  },
  {
    name: "Content Meister",
    category: "content distribution",
    language: "German",
    region: "Germany",
    product_type: "web 3.0",
    price: 1100,
  },
  {
    name: "Publicidade Total",
    category: "Ads",
    language: "Portuguese",
    region: "Brazil",
    product_type: "Gambling",
    price: 1000,
  },
  {
    name: "Influenceur Twitter",
    category: "twitter influencer",
    language: "French",
    region: "France",
    product_type: "adult",
    price: 2000,
  },
  {
    name: "टेलीग्राम प्रभावकार",
    category: "Telegram Influencer",
    language: "Hindi",
    region: "India",
    product_type: "web 3.0",
    price: 1500,
  },
  {
    name: "YouTube Infuencer",
    category: "Youtube influencers",
    language: "Russian",
    region: "Russia",
    product_type: "Gambling",
    price: 2300,
  },
  {
    name: "تأثير الإنستغرام",
    category: "instagram influencers",
    language: "Arabic",
    region: "UAE",
    product_type: "adult",
    price: 2500,
  },
];
